<?php

// Include all events, actions and conditions files
global $cre_includes;
$cre_includes = array ();
$dir = drupal_get_path ( 'module', 'commerce_rules_extra' );
foreach ( array ("events","conditions","actions") as $subdir ) {
	$cre_includes [$subdir] = glob ( "$dir/includes/$subdir/*.inc", GLOB_NOSORT );
	foreach ( $cre_includes [$subdir] as $include ) {
		include_once ($include);
	}
}


function commerce_rules_extra_get_quantity_property($order, array $options, $name) {
    $wrapper = entity_metadata_wrapper('commerce_order', $order);
    return commerce_line_items_quantity($wrapper->commerce_line_items, commerce_product_line_item_types());
}

